//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public int ID_Aluno { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string Endereco { get; set; }
        public string Celular { get; set; }
        public System.DateTime DataNasc { get; set; }
        public string Personal { get; set; }
    }
}
